/*
 * generated by Xtext 2.29.0
 */
package org.example.xbase.expressions.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.eclipse.xtext.xbase.typesystem.IBatchTypeResolver
import org.example.xbase.expressions.expressions.ExpressionsModel
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

import static extension org.junit.jupiter.api.Assertions.*

@ExtendWith(InjectionExtension)
@InjectWith(ExpressionsInjectorProvider)
class ExpressionsTypeComputerTest {

	@Inject extension ParseHelper<ExpressionsModel>
	@Inject IBatchTypeResolver typeResolver;

	@Test
	def void testEvalExpressionActualType() {
		'''
			val i = 0
			eval i
		'''.parse.expressions.last => [
			"java.lang.String".assertEquals(
				typeResolver.resolveTypes(it).getActualType(it).identifier
			)
		]
	}

}
