/*
 * generated by Xtext 2.29.0
 */
package org.example.customgreetings.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
class GreetingsProposalProvider extends AbstractGreetingsProposalProvider {
}
