/*
 * generated by Xtext 2.29.0
 */
package org.example.smalljava


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class SmallJavaRuntimeModule extends AbstractSmallJavaRuntimeModule {
}
