/*
 * generated by Xtext 2.29.0
 */
package org.example.xbase.expressions.ide


/**
 * Use this class to register ide components.
 */
class ExpressionsIdeModule extends AbstractExpressionsIdeModule {
}
