/*
 * generated by Xtext 2.29.0
 */
package org.example.smalljava.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class SmallJavaUiModule extends AbstractSmallJavaUiModule {
}
